source: www.jao.eu/download/archive/paragraph/545/field_attachments
geocode: True
regions:
  AT: AT
  CZ: CZ
  D2: DE
  D4_0: DE
  D8: DE
  FR: FR
  HR: HR
  HU: HU
  NL: NL
  PL: PL
  RO: RO
  SI: SI
  SK: SK
